library(DSOpal)
library(dsBaseClient)

builder <- DSI::newDSLoginBuilder()
builder$append(server = "study1", url = "http://192.168.57.101:8080", user = "administrator", password = "datashield_test&", table = "CNSIM.CNSIM1", driver = "OpalDriver")
builder$append(server = "study2", url = "http://192.168.57.101:8080", user = "administrator", password = "datashield_test&", table = "CNSIM.CNSIM2", driver = "OpalDriver")
builder$append(server = "study3", url = "http://192.168.57.101:8080", user = "administrator", password = "datashield_test&", table = "CNSIM.CNSIM3", driver = "OpalDriver")
logindata <- builder$build()

conns <- DSI::datashield.login(logins = logindata, assign = TRUE, symbol = "D")

print("ds.ls")
print(ds.ls(datasources = conns))
print(datashield.errors())
print("ds.dataFrame")
options(datashield.errors.stop = TRUE)
ds.dataFrame(c('D$GENDER'), newobj = 'df', datasources = conns[1])
print(datashield.errors())
print("ds.ls")
print(ds.ls(datasources = conns))
print("ds.asInteger")
ds.asInteger("df")
print("errors")
DSI::datashield.errors(conns = conns)
print("ds.ls")
print(ds.ls(datasources = conns))
print("logout")
DSI::datashield.logout(conns)

