---
title: "error testing"
output: html_notebook
---



# Libraries
```{r}
#Libraries 
library(DSI)
library(DSOpal)
library(httr)
library(ds.connect.client)
library(dsBaseClient)
```
# Only one server

```{r}
server.names      <- c("Paris", "NewYork", "Cambridge")
url_Paris         <- 'https://192.168.57.101:8443'
table_Paris       <- "TESTING.DATASET1"
user_Paris        <-  "administrator"
password_Paris    <-  "datashield_test&"
ssl_options_Paris <- "list(ssl_verifyhost=0,ssl_verifypeer=0)"
driver_Paris      <- "OpalDriver"


url_NewYork           <- 'https://192.168.56.100:8443'
table_NewYork         <- "TESTING.DATASET3"
user_NewYork          <-  "administrator"
password_NewYork      <-  "datashield_test&"
ssl_options_NewYork   <- "list(ssl_verifyhost=0,ssl_verifypeer=0)"
driver_NewYork        <- "OpalDriver"

url_Cambridge         <- 'https://opal-sandbox.mrc-epid.cam.ac.ukor'
table_Cambridge       <- "TESTING.DATASET2"
user_Cambridge        <-  "dsuser"
password_Cambridge    <-  "password"
ssl_options_Cambridge <- "list(ssl_verifyhost=0,ssl_verifypeer=0)"
driver_Cambridge      <- "OpalDriver"


server.urls       <- c(url_Paris, url_NewYork,url_Cambridge)
server.tables     <- c(table_Paris, table_NewYork,table_Cambridge)
server.users.id   <- c(user_Paris, user_NewYork, user_Cambridge)
server.users.pwd  <-  c(password_Paris, password_NewYork, password_Cambridge)
server.ssl.options <- c(ssl_options_Paris, ssl_options_NewYork, ssl_options_Cambridge)
server.drivers   <- c(driver_Paris,driver_NewYork,driver_Cambridge)
```


```{r}
login.data <- ds.build.login.data.frame(server.names,
                                        server.urls,
                                        server.tables,
                                        server.users.id,
                                        server.users.pwd,
                                        server.ssl.options,
                                        server.drivers)
print(login.data)
```

# set the server variables and login
```{R}
server.var <- list('ID','CHARACTER', 'LOGICAL','NA_VALUES','INTEGER','NULL_VALUES',
                   'NON_NEGATIVE_INTEGER','POSITIVE_INTEGER','NEGATIVE_INTEGER',
                   'NUMERIC', 'NON_NEGATIVE_NUMERIC','POSITIVE_NUMERIC','NEGATIVE_NUMERIC',
                   'FACTOR_CHARACTER','FACTOR_INTEGER','IDENTIFIER','CATEGORY','IDENTIFIER',
                   'CATEGORY')
connections <- ds.login(login.data, variables = server.var, symbol = 'D')
print(connections)
```

#test_errors
```{r}
server.function.call <- call('dimDS','D')
print(server.function.call)
outcome <- ds.aggregate(expression = server.function.call, asynchronous = FALSE, datasources = connections)
print(outcome)
```

```{r}
options(datashield.errors.stop = TRUE)
print(getOption("datashield.errors.stop"))
server.function.call <- call('test_errorDS')
print(server.function.call)
outcome <- ds.aggregate(expression = server.function.call, asynchronous = FALSE, datasources = connections)
print(outcome)
```


```{r}
options(datashield.errors.stop = FALSE)
print(getOption("datashield.errors.stop"))
server.function.call <- call('test_errorDS')
print(server.function.call)
outcome <- ds.aggregate(expression = server.function.call, asynchronous = FALSE, datasources = connections)
print(outcome)
```
```{r}
#FYI : paris should work.
# newyork should return an error
#
#test_mixed_errorDS <- function()
#{
#  if(getOption("TESTING") == 1)
#  {
#    stop(‘you are not allowed’)
#  }
#   
#  return(3.14)
#}
options(datashield.errors.stop = TRUE)
print(getOption("datashield.errors.stop"))
server.function.call <- call('test_mixed_errorDS')
print(server.function.call)
outcome <- ds.aggregate(expression = server.function.call, asynchronous = FALSE, datasources = connections)
print(outcome)
```

```{r}

```

#logout
```{R}
outcome <- ds.logout(connections)
print(outcome)
```