---
title: "error testing"
output: html_notebook
---



# Libraries
```{r}
#Libraries 
library(DSI)
library(DSOpal)
library(httr)
library(ds.connect.client)
library(dsBaseClient)
```
# Only one server

```{r}
server.names      <- c("Paris")
url_Paris         <- 'https://192.168.56.100:8443'
table_Paris       <- "TESTING.DATASET1"
user_Paris        <-  "administrator"
password_Paris    <-  "datashield_test&"
ssl_options_Paris <- "list(ssl_verifyhost=0,ssl_verifypeer=0)"
driver_Paris      <- "OpalDriver"

server.urls       <- c(url_Paris)
server.tables     <- c(table_Paris)
server.users.id   <- c(user_Paris)
server.users.pwd  <-  c(password_Paris)
server.ssl.options <- c(ssl_options_Paris)
server.drivers   <- c(driver_Paris)
```


```{r}
login.data <- ds.build.login.data.frame(server.names,
                                        server.urls,
                                        server.tables,
                                        server.users.id,
                                        server.users.pwd,
                                        server.ssl.options,
                                        server.drivers)
print(login.data)
```

# set the server variables and login
```{R}
server.var <- list('ID','CHARACTER', 'LOGICAL','NA_VALUES','INTEGER','NULL_VALUES',
                   'NON_NEGATIVE_INTEGER','POSITIVE_INTEGER','NEGATIVE_INTEGER',
                   'NUMERIC', 'NON_NEGATIVE_NUMERIC','POSITIVE_NUMERIC','NEGATIVE_NUMERIC',
                   'FACTOR_CHARACTER','FACTOR_INTEGER','IDENTIFIER','CATEGORY','IDENTIFIER',
                   'CATEGORY')
connections <- ds.login(login.data, variables = server.var, symbol = 'D')
print(connections)
```

#test_errors
```{r}
server.function.call <- call('dimDS','D')
print(server.function.call)
outcome <- ds.aggregate(expression = server.function.call, asynchronous = FALSE, datasources = connections)
print(outcome)
```

```{r}
server.function.call <- call('test_errorDS')
print(server.function.call)
outcome <- ds.aggregate(expression = server.function.call, asynchronous = FALSE, datasources = connections)
print(outcome)
```
```{r}
server.function.call <- call('test_mixed_errorDS')
print(server.function.call)
outcome <- ds.aggregate(expression = server.function.call, asynchronous = FALSE, datasources = connections)
print(outcome)
```
#logout
```{R}
outcome <- ds.logout(connections)
print(outcome)
```