---
title: "error testing"
output: html_notebook
---

# Libraries
```{r}
#Libraries 
library(DSI)
library(DSOpal)
library(httr)
library(dsConnectClient)
library(dsBaseClient)
```
# Only one server

```{r}
server.names      <- c("Paris", "NewYork")
url_Paris         <- 'https://192.168.57.101:8443'
table_Paris       <- "TESTING.DATASET1"
user_Paris        <-  "administrator"
password_Paris    <-  "datashield_test&"
ssl_options_Paris <- "list(ssl_verifyhost=0,ssl_verifypeer=0)"
driver_Paris      <- "OpalDriver"


url_NewYork   <- 'https://192.168.56.100:8443'
table_NewYork   <- "TESTING.DATASET3"
user_NewYork    <-  "administrator"
password_NewYork    <-  "datashield_test&"
ssl_options_NewYork   <- "list(ssl_verifyhost=0,ssl_verifypeer=0)"
driver_NewYork   <- "OpalDriver"


server.urls       <- c(url_Paris, url_NewYork)
server.tables     <- c(table_Paris, table_NewYork)
server.users.id   <- c(user_Paris, user_NewYork)
server.users.pwd  <-  c(password_Paris, password_NewYork)
server.ssl.options <- c(ssl_options_Paris, ssl_options_NewYork)
server.drivers   <- c(driver_Paris,driver_NewYork)
```


```{r}
login.data <- ds.build.login.data.frame(server.names,
                                        server.urls,
                                        server.tables,
                                        server.users.id,
                                        server.users.pwd,
                                        server.ssl.options,
                                        server.drivers)
print(login.data)
```

# set the server variables and login
```{R}
server.var <- list('ID','CHARACTER', 'LOGICAL','NA_VALUES','INTEGER','NULL_VALUES',
                   'NON_NEGATIVE_INTEGER','POSITIVE_INTEGER','NEGATIVE_INTEGER',
                   'NUMERIC', 'NON_NEGATIVE_NUMERIC','POSITIVE_NUMERIC','NEGATIVE_NUMERIC',
                   'FACTOR_CHARACTER','FACTOR_INTEGER','IDENTIFIER','CATEGORY','IDENTIFIER',
                   'CATEGORY')
connections <- ds.login(login.data, variables = server.var, symbol = 'D')
print(connections)
```

#test_errors
sanity check
```{r}
server.function.call <- call('dimDS','D')
print(server.function.call)
outcome <- ds.aggregate(expression = server.function.call, asynchronous = FALSE, datasources = connections)
print(outcome)
```
```{r}

server.function.call <- call('dimDS','D')
print(server.function.call)
outcome <- ds.aggregate(expression = server.function.call, asynchronous = FALSE, error.stop = FALSE, datasources = connections)
print(outcome)
```

```{r}
options(datashield.errors.stop = TRUE)
print(getOption("datashield.errors.stop"))
server.function.call <- call('test_errorDS')
print(server.function.call)
outcome <- ds.aggregate(expression = server.function.call, asynchronous = FALSE, error.stop = TRUE, datasources = connections)
print(outcome)
```


```{r}
server.function.call <- call('test_errorDS')
print(server.function.call)
outcome <- ds.aggregate(expression = server.function.call, asynchronous = FALSE, error.stop = FALSE, datasources = connections)
print(outcome)
```
FYI : paris should work.
 newyork should return an error

test_mixed_errorDS <- function()
{
  if(getOption("TESTING") == 1)
  {
    stop(‘you are not allowed’)
  }
  
  return(3.14)
}
```{r}


server.function.call <- call('test_mixed_errorDS')
print(server.function.call)
outcome <- ds.aggregate(expression = server.function.call, asynchronous = FALSE, datasources = connections)
print(outcome)
```

```{r}

server.function.call <- call('test_mixed_errorDS')
print(server.function.call)
outcome <- ds.aggregate(expression = server.function.call, asynchronous = FALSE, error.stop = FALSE, datasources = connections)
print(outcome)
```

#assign

sanity check

```{r}
#lsDS<-function(search.filter=NULL,env.to.search)
server.function.call <- call('lsDS', NULL,".GlobalEnv")
print(server.function.call)
outcome <- ds.aggregate(expression = server.function.call, asynchronous = FALSE, error.stop = TRUE, datasources = connections)
print(outcome)
```
```{r}
DSI::datashield.assign(conns = connections, symbol = "aPieInTheSky", value = as.symbol("D$INTEGER"), async = FALSE)
print(DSI::datashield.errors())
```
<span style='color:purple'><b>Results shown in the console:
Assigned expr. (aPieInTheSky <- D$INTEGER) [===========================================] 100% / 2s
Error: There are some DataSHIELD errors, list them with datashield.errors()</b></span>



```{r}
#lsDS<-function(search.filter=NULL,env.to.search)
server.function.call <- call('lsDS', NULL,".GlobalEnv")
print(server.function.call)
outcome <- ds.aggregate(expression = server.function.call, asynchronous = FALSE, error.stop = TRUE, datasources = connections)
print(outcome)
```

```{r}
#rNormDS<-function (n, mean = 0, sd = 1, force.output.to.k.decimal.places=9)
#server.function.call <- call('rNormDS',1000)
#DSI::datashield.assign(conns = connections, symbol = "aNormDist1", value = server.function.call, async = FALSE)
#print(datashield.errors())
```

```{r}

#rUnifDS<-function (n, min = 0, max = 1, force.output.to.k.decimal.places=9)
#server.function.call <- call('rUnifDS',1000)
#print(server.function.call)
#outcome <- ds.assign.value(new.variable.name = "aRunifDist", 
#                           value = server.function.call, 
#                           class.type = "numeric", 
#                           asynchronous = FALSE, 
#                           error.stop = TRUE, 
#                           datasources = connections)
#print(outcome)
```

```{r}
#rNormDS<-function (n, mean = 0, sd = 1, force.output.to.k.decimal.places=9)
#server.function.call <- call('rNormDS',1000)
#print(server.function.call)
#outcome <- ds.assign.value(new.variable.name = "aNormDist", 
#                           value = server.function.call, 
#                           class.type = "numeric", 
#                           asynchronous = FALSE, 
#                           error.stop = TRUE, 
#                           datasources = connections)
#print(outcome)
```


```{r}
#lsDS<-function(search.filter=NULL,env.to.search)
#server.function.call <- call('lsDS', NULL,".GlobalEnv")
#print(server.function.call)
#outcome <- ds.aggregate(expression = server.function.call, asynchronous = FALSE, error.stop = TRUE, datasources = connections)
#print(outcome)
```


```{r}
#server.function.call <- call('test_assign_errorDS')
#print(server.function.call)
#outcome <- ds.assign.value(new.variable.name = "aPie", 
#                           value = server.function.call, 
#                           class.type = "numeric", 
#                           asynchronous = FALSE, 
#                           error.stop = TRUE, 
#                           datasources = connections)
#print(outcome)
```


#logout
```{R}
outcome <- ds.logout(connections)
print(outcome)
```